### ISSUE TITLE
Tracker público de torrent

### ISSUE THREAD

**Issue by exos** [rlyehlab/infra-issues#3]
Sin contenidos, pero el tracker.

**Comment by HacKanCuBa** [comment]
Hmm ¿para qué? :P

**Comment by HacKanCuBa** [comment]
Habría que ver que no nos morfe el BW ni conlleve inconvenientes legales... ¿queda para asamblea?

**Comment by exos** [comment]
No creo que morfe mucho BW, consideremos que es un tracker nada mas. Sobre temas legales:

1- Es un tracker, no contendría nada ilegal
2- En Argentina no es ilegal torrent

**Comment by HacKanCuBa** [comment]
Joya, arrobate 2 admines más que te den una mano, te hacés cargo de administrar la VM.
¿Qué caracteristicas requerís para esta VM?

¿Opiniones? Ping @rlyehlab/infra

**Comment by Fas0x** [comment]
Genial, con las caracteristicas necesarias podemos levantar esta VM en la proxima reunion.
