### ISSUE TITLE
Sitio ETER

### ISSUE THREAD

**Issue by thessaly** [rlyehlab/infra-issues#5]
Crear VM: 

- 1 gb ram
- 2 gb disco
- SO ubuntu
- 2 cores
- Pasar llaves ssh admin

Dominio: etermonitor.net

**Comment by thessaly** [comment]
@violenti llaves ssh

**Comment by HacKanCuBa** [comment]
Solicitado por proyecto del lab. Solicitud aceptada en el lab ayer.

**Comment by HacKanCuBa** [comment]
VM definida: `miniac`

**Comment by lmaddio** [comment]
@cuerdo 
1) Contenedor base de datos PostgreSQL.
2) Contenedor para Broker [Mosquitto](https://mosquitto.org/).
3) Contenedor app para escribir en la base App en Python, Flask
4) Contenedor app para leer la base [App en NodeJs](https://nodejs.org/es/), [Graphql](https://graphql.org/learn/), [Postgraphile](https://github.com/graphile/postgraphile) y exportar una API para la web.
5) Aplicacion web (NodeJs, [React](https://reactjs.org/docs/add-react-to-a-new-app.html), [create-react-app](https://github.com/facebook/create-react-app) y [Webpack](https://webpack.js.org/)).
